### ISSUE TITLE
Install on ubuntu 22.04

### ISSUE THREAD

**Issue by YiChenCityU** [ultravideo/Open3DGen#14]
1. gtsam install:
git checkout tags/4.0.2 ;

Error： 
/Open3DGen/src/texture_projector.cpp:403:10: error: ‘atomic_int’ is not a member of ‘std’
403 |     std::atomic_int success_count = 0;
Fix：texture_projector.cpp，加入#include <**std::atomic_int**>

Error： 
/usr/local/include/gtsam/base/Vector.h:76:30: error: static assertion failed: Error: GTSAM was built against a different version of Eigen
76 |     GTSAM_EIGEN_VERSION_MAJOR==EIGEN_MAJOR_VERSION,
Fix：
Firstly cmake -DGTSAM_USE_SYSTEM_EIGEN=ON -DGTSAM_WITH_TBB=OFF .. ; but still get the error. So I decide to comment the code below in base/Vector.h

//static_assert(
//   GTSAM_EIGEN_VERSION_WORLD==EIGEN_WORLD_VERSION &&
//   GTSAM_EIGEN_VERSION_MAJOR==EIGEN_MAJOR_VERSION,
// "Error: GTSAM was built against a different version of Eigen");

2. open3D install 
Error：
Open3DGen/src/math_modules.h:2:10: fatal error: Open3D/Open3D.h: No such file or directory
2 | #include <Open3D/Open3D.h>
Fix： Because the version of open3D which install by libopen3d-dev on ubuntu 22.04 is 0.14.0. The structure has changed alot. So checkout to 0.9.0 and install with source code.  git checkout tags/v0.9.0 

Error：
Open3D/3rdparty/pybind11/include/pybind11/pybind11.h:2036:30: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
2036 |             frame->f_locals, PyTuple_GET_ITEM(frame->f_code->co_varnames, 0));
Fix： cmake .. -DBUILD_PYBIND11=OFF -DBUILD_CPP_EXAMPLES=OFF  ，Because the version of python on ubuntu is not compatible with the pybind11. 

![image](https://github.com/ultravideo/Open3DGen/assets/12424523/dde70376-59ce-4db9-81ec-3dada4bb70f0)

**Comment by fador** [comment]
I made a new branch [open3d-0.18](https://github.com/ultravideo/Open3DGen/tree/open3d-0.18) that works in ubuntu 24.04
