### ISSUE TITLE
Build problem in Ubuntu18.04

### ISSUE THREAD

**Issue by Z-Jeff** [ultravideo/Open3DGen#6]
Because _apt_ can't install libopen3d-dev on Ubuntu18.04, I have build and install open3d from source. 
Here is my steps:
```
git clone https://github.com/isl-org/Open3D 
cd Open3D
mkdir build 
cd build 
cmake .. -DBUILD_PYTHON_MODULE=OFF  -DBUILD_CUDA_MODULE=ON 
make 
sudo make install
```
Then, I run _./build.sh_ in Open3DGen, some errors occur like:
`fatal error: Open3D/Open3D.h: No such file or directory`
I replace `#include<Open3D/Open3D.h>` with `#include<open3d/Open3D.h>` , more error like `error: ‘registration’ is not a member of ‘stitcher3d::o3d’` occur.
How can I fix this?
By the way, is there a proper way to install Open3D in ubuntu18.04?

**Comment by gmikeup** [comment]
I tried on ubuntu22.04, also the same problem as 'fatal error: Open3D/Open3D.h: No such file or directory', it seemed that 
 related with libopen3d-dev . I tried to change the path in the<Open3DGen-main/src/surface_mesh.h> .h or main.cpp files, but still report :Open3DGen-main/src/constants.h:130:89: error: ‘registration’ is not a member of ‘stitcher3d::o3d’
  130 |     typedef std::tuple<std::shared_ptr<o3d::geometry::PointCloud>, std::shared_ptr<o3d::registration::Feature>> down_fpfh;
There might be a lot of work to deal with Open3D versions.
Open3DGen compile with Open3D in Older versions like 0.9.0 or 0.10.0 may work fine. 
But on ubuntu22.04 can only find 0.14.1 version.
I tried to install 0.9.0 by deb but met dependency problems.
Then I'm trying  ubuntu21.10, which can install libopen3d-dev_0.9.0+ds-5build2 by default.

**Comment by jiajigiser** [comment]
> I tried on ubuntu22.04, also the same problem as 'fatal error: Open3D/Open3D.h: No such file or directory', it seemed that related with libopen3d-dev . I tried to change the path in the<Open3DGen-main/src/surface_mesh.h> .h or main.cpp files, but still report :Open3DGen-main/src/constants.h:130:89: error: ‘registration’ is not a member of ‘stitcher3d::o3d’ 130 | typedef std::tuple<std::shared_ptro3d::geometry::PointCloud, std::shared_ptro3d::registration::Feature> down_fpfh; There might be a lot of work to deal with Open3D versions. Open3DGen compile with Open3D in Older versions like 0.9.0 or 0.10.0 may work fine. But on ubuntu22.04 can only find 0.14.1 version. I tried to install 0.9.0 by deb but met dependency problems. Then I'm trying ubuntu21.10, which can install libopen3d-dev_0.9.0+ds-5build2 by default.

**Comment by jiajigiser** [comment]
> I tried on ubuntu22.04, also the same problem as 'fatal error: Open3D/Open3D.h: No such file or directory', it seemed that related with libopen3d-dev . I tried to change the path in the<Open3DGen-main/src/surface_mesh.h> .h or main.cpp files, but still report :Open3DGen-main/src/constants.h:130:89: error: ‘registration’ is not a member of ‘stitcher3d::o3d’ 130 | typedef std::tuple<std::shared_ptro3d::geometry::PointCloud, std::shared_ptro3d::registration::Feature> down_fpfh; There might be a lot of work to deal with Open3D versions. Open3DGen compile with Open3D in Older versions like 0.9.0 or 0.10.0 may work fine. But on ubuntu22.04 can only find 0.14.1 version. I tried to install 0.9.0 by deb but met dependency problems. Then I'm trying ubuntu21.10, which can install libopen3d-dev_0.9.0+ds-5build2 by default.

Have you finally resolved it？
